name: Reformat

on: [workflow_call]

permissions:
  contents: write

jobs:
  lint:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - name: Set up Python
        uses: actions/setup-python@v5
        with:
          python-version: 3.12
      - name: Install dependencies
        run: |
          python -m pip install --upgrade pip
          pip install black
      - name: Reformat code
        run: |
          black .
      - name: Check for changes
        id: check-for-changes
        run: |
          if [ -z "$(git status --porcelain)" ]; then \
            echo "has_changes=false" >> $GITHUB_OUTPUT \
          else \
            echo "has_changes=true" >> $GITHUB_OUTPUT \
          fi
      - name: Commit and push changes
        if: steps.check-for-changes.outputs.has_changes == 'true'
        run: |
          git config --global user.email "41898282+github-actions[bot]@users.noreply.github.com"
          git config --global user.name "github-actions[bot]"
          git add .
          git commit -m "refactor: Auto reformat code"
          git push