name: release-please

on:
  push:
    branches:
      - main

permissions: read-all

jobs:
  release-please:
    runs-on: ubuntu-latest
    steps:
      - uses: google-github-actions/release-please-action@v4
        with:
          release-type: python
