name: Validate

on:
  push:
    branches:
      - develop

jobs:
  reformat:
    uses: ./.github/workflows/reformat.yaml
    permissions:
      contents: write
  lint:
    uses: ./.github/workflows/lint.yaml
