name: Validate and Merge

on:
  push:
    branches:
      - develop

jobs:
  reformat:
    uses: ./.github/workflows/reformat.yaml
    permissions:
      contents: write
  lint:
    needs: reformat
    uses: ./.github/workflows/lint.yaml
  unit-test:
    needs: reformat
    uses: ./.github/workflows/unit-test.yaml
  merge:
    needs: [reformat, lint, unit-test]
    uses: ./.github/workflows/merge.yaml
    with:
      target_branch: main
    permissions:
      contents: write
