name: Validate

on:
  push:
    branches:
      - develop
  pull_request:
    branches:
      - develop

jobs:
  reformat:
    uses: ./.github/workflows/reformat.yaml
  lint:
    uses: ./.github/workflows/lint.yaml